### ISSUE TITLE
The example it's not working in QE49Q60RATXXC (QLED 2019)

### ISSUE THREAD

**Issue by avelad** [SamsungDForum/voice-mediacontrols#1]
I tried to run the example in QE49Q60RATXXC and it's not working. tizen.bixby is missing, but the TV has bixby. Is anything else necessary?

**Comment by bfaru** [comment]
@avelad you're supposed to call `webapis.bixby` as the readme mentions instead of `tizen.bixby`. This sample is a little misleading since `video.js` uses `tizen.bixby`.

**Comment by xiaosenmao** [comment]
@bfaru Hi. 
I debug my tizen-web-app on TV UN49RU8000F which **supports** Bixby, and found some issues.
Please refer to the following screenshot：
![a](https://user-images.githubusercontent.com/31017346/81802444-ab290e80-9548-11ea-8c52-63189afe8cdb.png)
![b](https://user-images.githubusercontent.com/31017346/81802455-af552c00-9548-11ea-9166-07a02f2a76cc.png)

**Comment by xiaosenmao** [comment]
I don't find the reason of **WebAPIException**
